package leetcode.HashTable;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 */
public class FindTheDifference {
    public static void main(String[] args) {

    }

    //using array as the hashmap
    public char findTheDifference(String s, String t) {
        int[] records = new int[26];

        for (int i = 0; i < s.length(); i++) {
            int index = s.charAt(i) - 'a';
            records[index]++;
        }

        for (int i = 0; i < t.length(); i++) {
            int index = t.charAt(i) - 'a';
            records[index]--;
        }

        for (int i = 0; i < 26; i++) {
            if (records[i] < 0) {
                return (char) ('a' + i);
            }
        }

        return ' ';
    }
}
